---
- name: Ensure required Python packages are installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: present
    virtualenv: "{{ ironic_inspector_venv }}"
  with_items:
    - name: python-ironic-inspector-client

- name: Activate the virtualenv
  include_role:
    name: activate-virtualenv
  vars:
    activate_virtualenv_path: "{{ ironic_inspector_venv }}"

- name: Ensure introspection rules exist
  os_ironic_inspector_rule:
    auth_type: "{{ ironic_inspector_auth_type }}"
    auth: "{{ ironic_inspector_auth }}"
    conditions: "{{ item.conditions }}"
    actions: "{{ item.actions }}"
    description: "{{ item.description | default(omit) }}"
    uuid: "{{ item.uuid | default(item.description | to_uuid) | default(omit) }}"
    state: present
    inspector_url: "{{ ironic_inspector_url }}"
  with_items: "{{ ironic_inspector_rules }}"

- name: Deactivate the virtualenv
  include_role:
    name: deactivate-virtualenv
