---
# Path to directory for kolla-ansible source code checkout.
kolla_ansible_source_path:

# Type of Kolla-ansible control installation. One of 'binary' or 'source'.
kolla_ansible_ctl_install_type:

# URL of Kolla Ansible source code repository if type is 'source'.
kolla_ansible_source_url:

# Version (branch, tag, etc.) of Kolla Ansible source code repository if type
# is 'source'.
kolla_ansible_source_version:

# Virtualenv directory where Kolla-ansible will be installed.
kolla_ansible_venv: "{{ ansible_env['PWD'] }}/kolla-venv"

# Virtualenv directory where Kolla-ansible's ansible modules will execute
# remotely on the target nodes. If None, no virtualenv will be used.
kolla_ansible_target_venv:

# Upper constraints file which is passed to pip when installing packages
# into the kolla-ansible venv.
kolla_upper_constraints_file:

# Password to use to encrypt the passwords.yml file.
kolla_ansible_vault_password:

# Directory where Kolla config files will be installed.
kolla_config_path:

# Directory where Kolla custom configuration files will be installed.
kolla_node_custom_config_path:

# Path to kolla-ansible passwords.yml input file.
kolla_ansible_passwords_path:

###############################################################################
# Kolla-ansible inventory configuration.

# Full custom seed inventory contents.
kolla_seed_inventory_custom:

# Custom overcloud inventory containing a mapping from top level groups to
# hosts.
kolla_overcloud_inventory_custom_top_level:

# Custom overcloud inventory containing a mapping from components to top level
# groups.
kolla_overcloud_inventory_custom_components:

# Custom overcloud inventory containing a mapping from services to components.
kolla_overcloud_inventory_custom_services:

# Full custom overcloud inventory contents. By default this will be the
# concatenation of the top level, component, and service inventories.
kolla_overcloud_inventory_custom:

# Dict mapping from kolla-ansible groups to kayobe groups and variables. Each
# item is a dict with the following items:
# * groups: A list of kayobe ansible groups to map to this kolla-ansible group.
# * vars: A dict mapping variable names to values for hosts in this
#         kolla-ansible group.
kolla_overcloud_inventory_top_level_group_map: {}

# List of names of top level kolla-ansible groups. Any of these groups which
# have no hosts mapped to them will be provided with an empty group definition.
kolla_overcloud_inventory_kolla_top_level_groups: []

# List of names of host variables to pass through from kayobe hosts to
# kolla-ansible hosts, if set.
kolla_overcloud_inventory_pass_through_host_vars:
  - "ansible_host"
  - "ansible_port"
  - "ansible_ssh_private_key_file"
  - "kolla_api_interface"

###############################################################################
# Kolla-ansible global configuration options.

# Valid options are [ centos, fedora, oraclelinux, ubuntu ]
kolla_base_distro:

# Valid options are [ binary, source ]
kolla_install_type:

# Docker namespace to use for Kolla images.
kolla_docker_namespace:

# Url of docker registry to use for Kolla images.
kolla_docker_registry:

# Username to use to access a docker registry.
kolla_docker_registry_username:

# Password to use to access a docker registry.
kolla_docker_registry_password:

# Valid option is Docker repository tag
kolla_openstack_release:

# This should be a VIP, an unused IP on your network that will float between
# the hosts running keepalived for high-availability. When running an All-In-One
# without haproxy and keepalived, this should be the first IP on your
# 'network_interface' as set in the Networking section below.
kolla_internal_vip_address:

# This is the DNS name that maps to the kolla_internal_vip_address VIP. By
# default it is the same as kolla_internal_vip_address.
kolla_internal_fqdn:

# This should be a VIP, an unused IP on your network that will float between
# the hosts running keepalived for high-availability. It defaults to the
# kolla_internal_vip_address, allowing internal and external communication to
# share the same address.  Specify a kolla_external_vip_address to separate
# internal and external requests between two VIPs.
kolla_external_vip_address:

# The Public address used to communicate with OpenStack as set in the public_url
# for the endpoints that will be created. This DNS name should map to
# kolla_external_vip_address.
kolla_external_fqdn:


####################
# Networking options
####################
# This interface is what all your api services will be bound to by default.
# Additionally, all vxlan/tunnel and storage network traffic will go over this
# interface by default. This interface must contain an IPv4 address.
# It is possible for hosts to have non-matching names of interfaces - these can
# be set in an inventory file per host or per group or stored separately, see
#     http://docs.ansible.com/ansible/intro_inventory.html
# Yet another way to workaround the naming problem is to create a bond for the
# interface on all hosts and give the bond name here. Similar strategy can be
# followed for other types of interfaces.
kolla_network_interface:

# These can be adjusted for even more customization. The default is the same as
# the 'network_interface'. These interfaces must contain an IPv4 address.
kolla_external_vip_interface:
kolla_api_interface:
kolla_storage_interface:
kolla_cluster_interface:
kolla_dns_interface:

# This is the raw interface given to neutron as its external network port. Even
# though an IP address can exist on this interface, it will be unusable in most
# configurations. It is recommended this interface not be configured with any IP
# addresses for that reason.
# This should be a list of names of interfaces.
kolla_neutron_external_interfaces: []

# List of names of Neutron bridges.
kolla_neutron_bridge_names: []

# This is the interface to use for Bifrost bare metal provisioning of the
# control plane.
kolla_bifrost_network_interface:

# This is the interface to use for bare metal provisioning. It is not a
# standard kolla variable.
kolla_provision_interface:

# Interface on which the inspector dnsmasq service listens.
kolla_inspector_dnsmasq_interface:

# List of Neutron ML2 type drivers to use.
kolla_neutron_ml2_type_drivers: []

# List of Neutron ML2 tenant network types to use.
kolla_neutron_ml2_tenant_network_types: []

####################
# TLS options
####################
# To provide encryption and authentication on the kolla_external_vip_interface,
# TLS can be enabled.  When TLS is enabled, certificates must be provided to
# allow clients to perform authentication.
kolla_enable_tls_external:
kolla_external_fqdn_cert:


####################
# OpenStack options
####################
# Use these options to set the various log levels across all OpenStack projects
# Valid options are [ True, False ]
kolla_openstack_logging_debug:

# OpenStack services can be enabled or disabled with these options
#kolla_enable_aodh:
#kolla_enable_barbican:
#kolla_enable_ceilometer:
#kolla_enable_central_logging:
#kolla_enable_ceph:
#kolla_enable_ceph_rgw:
#kolla_enable_cinder:
#kolla_enable_cinder_backend_iscsi:
#kolla_enable_cinder_backend_lvm:
#kolla_enable_cloudkitty:
#kolla_enable_congress:
#kolla_enable_etcd:
#kolla_enable_gnocchi:
#kolla_enable_grafana:
#kolla_enable_heat:
#kolla_enable_horizon:
#kolla_enable_influxdb:
#kolla_enable_ironic:
#kolla_enable_kafka:
#kolla_enable_kuryr:
#kolla_enable_magnum:
#kolla_enable_manila:
#kolla_enable_mistral:
#kolla_enable_monasca:
#kolla_enable_mongodb:
#kolla_enable_murano:
#kolla_enable_multipathd:
#kolla_enable_neutron_dvr:
#kolla_enable_neutron_lbaas:
#kolla_enable_neutron_qos:
#kolla_enable_neutron_agent_ha:
#kolla_enable_neutron_vpnaas:
#kolla_enable_rally:
#kolla_enable_sahara:
#kolla_enable_senlin:
#kolla_enable_swift:
#kolla_enable_telegraf:
#kolla_enable_tempest:
#kolla_enable_watcher:
#kolla_enable_zookeeper:

#######################
# Nova options
#######################

# Which host to use to deploy the nova-compute services for ironic. By default
# this is none and all hosts in the nova group are used instead - typically the
# controllers.
kolla_nova_compute_ironic_host:

###############################################################################
# Extra free-form configuraton.

# Free form extra configuration to append to {{ kolla_config_path }}/globals.yml.
kolla_extra_globals:

# Dictionary containing custom passwords to add or override in the Kolla
# passwords file.
kolla_ansible_custom_passwords: {}
