---
# List of custom configuration directories.
# Each item is a dict containing the following items:
# src: Path to directory containing configuration file templates.
# dest: Path to directory in which generated files will be created.
# patterns: One or more file name patterns to match.
# enabled: Whether these files should be templated.
# ignore: Optional list of files to leave in the destination, even if disabled
#         or unexpected.
kolla_openstack_custom_config:
  # Ceph.
  - src: "{{ kolla_extra_config_path }}/ceph"
    dest: "{{ kolla_node_custom_config_path }}/ceph"
    patterns: "*"
    enabled: "{{ kolla_enable_ceph }}"  
  # Fluentd filters.
  - src: "{{ kolla_extra_config_path }}//fluentd/filter"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/filter"
    patterns: "*.conf"
    enabled: True
  # Fluentd outputs.
  - src: "{{ kolla_extra_config_path }}/fluentd/output"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/output"
    patterns: "*.conf"
    enabled: True
  # Glance.
  - src: "{{ kolla_extra_config_path }}/glance"
    dest: "{{ kolla_node_custom_config_path }}/glance"
    patterns: "*"
    enabled: "{{ kolla_enable_glance }}"
  # Heat.
  - src: "{{ kolla_extra_config_path }}/heat"
    dest: "{{ kolla_node_custom_config_path }}/heat"
    patterns: "*"
    enabled: "{{ kolla_enable_heat }}"
  # Ironic.
  - src: "{{ kolla_extra_config_path }}/ironic"
    dest: "{{ kolla_node_custom_config_path }}/ironic"
    patterns: "*"
    enabled: "{{ kolla_enable_ironic }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ironic-agent.initramfs
      - ironic-agent.kernel
      - ironic-dnsmasq.conf
      - pxelinux.default
  # Keystone.
  - src: "{{ kolla_extra_config_path }}/keystone"
    dest: "{{ kolla_node_custom_config_path }}/keystone"
    patterns: "*"
    enabled: True
  # Magnum.
  - src: "{{ kolla_extra_config_path }}/magnum"
    dest: "{{ kolla_node_custom_config_path }}/magnum"
    patterns: "*"
    enabled: "{{ kolla_enable_magnum }}"
  # Murano.
  - src: "{{ kolla_extra_config_path }}/murano"
    dest: "{{ kolla_node_custom_config_path }}/murano"
    patterns: "*"
    enabled: "{{ kolla_enable_murano }}"
  # Neutron.
  - src: "{{ kolla_extra_config_path }}/neutron"
    dest: "{{ kolla_node_custom_config_path }}/neutron"
    patterns: "*"
    enabled: "{{ kolla_enable_neutron }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ml2_conf.ini
  # Nova.
  - src: "{{ kolla_extra_config_path }}/nova"
    dest: "{{ kolla_node_custom_config_path }}/nova"
    patterns: "*"
    enabled: "{{ kolla_enable_nova }}"
  # Sahara.
  - src: "{{ kolla_extra_config_path }}/sahara"
    dest: "{{ kolla_node_custom_config_path }}/sahara"
    patterns: "*"
    enabled: "{{ kolla_enable_sahara }}"
  # Swift.
  - src: "{{ kolla_extra_config_path }}/swift"
    dest: "{{ kolla_node_custom_config_path }}/swift"
    patterns: "*"
    enabled: "{{ kolla_enable_swift }}" 
