---
# List of custom configuration directories.
# Each item is a dict containing the following items:
# src: Path to directory containing configuration file templates.
# dest: Path to directory in which generated files will be created.
# patterns: One or more file name patterns to match.
# enabled: Whether these files should be templated.
# ignore: Optional list of files to ignore. These files will not be copied to
#         the destination, and will not be removed from the destination, even
#         if disabled or unexpected.
kolla_openstack_custom_config:
  # Barbican.
  - src: "{{ kolla_extra_config_path }}/barbican"
    dest: "{{ kolla_node_custom_config_path }}/barbican"
    patterns: "*"
    enabled: "{{ kolla_enable_barbican }}"
  # Ceph.
  - src: "{{ kolla_extra_config_path }}/ceph"
    dest: "{{ kolla_node_custom_config_path }}/ceph"
    patterns: "*"
    enabled: "{{ kolla_enable_ceph }}"
  # Cinder.
  - src: "{{ kolla_extra_config_path }}/cinder"
    dest: "{{ kolla_node_custom_config_path }}/cinder"
    patterns: "*"
    enabled: "{{ kolla_enable_cinder }}"
  # Designate.
  - src: "{{ kolla_extra_config_path }}/designate"
    dest: "{{ kolla_node_custom_config_path }}/designate"
    patterns: "*"
    enabled: "{{ kolla_enable_designate }}"
  # Fluentd filters.
  - src: "{{ kolla_extra_config_path }}//fluentd/filter"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/filter"
    patterns: "*.conf"
    enabled: true
  # Fluentd inputs.
  - src: "{{ kolla_extra_config_path }}//fluentd/input"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/input"
    patterns: "*.conf"
    enabled: true
  # Fluentd outputs.
  - src: "{{ kolla_extra_config_path }}/fluentd/output"
    dest: "{{ kolla_node_custom_config_path }}/fluentd/output"
    patterns: "*.conf"
    enabled: true
  # Glance.
  - src: "{{ kolla_extra_config_path }}/glance"
    dest: "{{ kolla_node_custom_config_path }}/glance"
    patterns: "*"
    enabled: "{{ kolla_enable_glance }}"
  # Grafana.
  - src: "{{ kolla_extra_config_path }}/grafana"
    dest: "{{ kolla_node_custom_config_path }}/grafana"
    patterns: "*"
    enabled: "{{ kolla_enable_grafana }}"
  # Heat.
  - src: "{{ kolla_extra_config_path }}/heat"
    dest: "{{ kolla_node_custom_config_path }}/heat"
    patterns: "*"
    enabled: "{{ kolla_enable_heat }}"
  # Horizon.
  - src: "{{ kolla_extra_config_path }}/horizon"
    dest: "{{ kolla_node_custom_config_path }}/horizon"
    patterns: "*"
    enabled: "{{ kolla_enable_horizon }}"
  # InfluxDB.
  - src: "{{ kolla_extra_config_path }}/"
    dest: "{{ kolla_node_custom_config_path }}/"
    patterns: "influx*"
    enabled: "{{ kolla_enable_influxdb }}"
  # Storm.
  - src: "{{ kolla_extra_config_path }}/storm"
    dest: "{{ kolla_node_custom_config_path }}/storm"
    patterns: "*"
    enabled: "{{ kolla_enable_storm }}"
  # Ironic.
  - src: "{{ kolla_extra_config_path }}/ironic"
    dest: "{{ kolla_node_custom_config_path }}/ironic"
    patterns: "*"
    enabled: "{{ kolla_enable_ironic }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ironic-agent.initramfs
      - ironic-agent.kernel
      - ironic-dnsmasq.conf
      - pxelinux.default
      - inspector.ipxe
  # Kafka.
  - src: "{{ kolla_extra_config_path }}/kafka"
    dest: "{{ kolla_node_custom_config_path }}/kafka"
    patterns: "*"
    enabled: "{{ kolla_enable_kafka }}"
  # Keystone.
  - src: "{{ kolla_extra_config_path }}/keystone"
    dest: "{{ kolla_node_custom_config_path }}/keystone"
    patterns: "*"
    enabled: true
  # Magnum.
  - src: "{{ kolla_extra_config_path }}/magnum"
    dest: "{{ kolla_node_custom_config_path }}/magnum"
    patterns: "*"
    enabled: "{{ kolla_enable_magnum }}"
  # Manila.
  - src: "{{ kolla_extra_config_path }}/manila"
    dest: "{{ kolla_node_custom_config_path }}/manila"
    patterns: "*"
    enabled: "{{ kolla_enable_manila }}"
  # MariaDB.
  - src: "{{ kolla_extra_config_path }}/mariadb"
    dest: "{{ kolla_node_custom_config_path }}/mariadb"
    patterns: "*"
    enabled: "{{ kolla_enable_mariadb }}"
  # Monasca.
  - src: "{{ kolla_extra_config_path }}/monasca"
    dest: "{{ kolla_node_custom_config_path }}/monasca"
    patterns: "*"
    enabled: "{{ kolla_enable_monasca }}"
  # Murano.
  - src: "{{ kolla_extra_config_path }}/murano"
    dest: "{{ kolla_node_custom_config_path }}/murano"
    patterns: "*"
    enabled: "{{ kolla_enable_murano }}"
  # Neutron.
  - src: "{{ kolla_extra_config_path }}/neutron"
    dest: "{{ kolla_node_custom_config_path }}/neutron"
    patterns: "*"
    enabled: "{{ kolla_enable_neutron }}"
    ignore:
      # These are templated by kayobe, so don't remove them.
      - ml2_conf.ini
  # Nova.
  - src: "{{ kolla_extra_config_path }}/nova"
    dest: "{{ kolla_node_custom_config_path }}/nova"
    patterns: "*"
    enabled: "{{ kolla_enable_nova }}"
  # Sahara.
  - src: "{{ kolla_extra_config_path }}/sahara"
    dest: "{{ kolla_node_custom_config_path }}/sahara"
    patterns: "*"
    enabled: "{{ kolla_enable_sahara }}"
  # Swift.
  - src: "{{ kolla_extra_config_path }}/swift"
    dest: "{{ kolla_node_custom_config_path }}/swift"
    patterns: "*"
    enabled: "{{ kolla_enable_swift }}"
  # Zookeeper.
  - src: "{{ kolla_extra_config_path }}/zookeeper"
    dest: "{{ kolla_node_custom_config_path }}/zookeeper"
    patterns: "*"
    enabled: "{{ kolla_enable_zookeeper }}"
