---
# Glean/simple-init is useful for reading configdrive data when provisioning
# servers but gets in the way after this as it tries to enable all network
# interfaces. In some cases this can lead to timeouts.
- name: Ensure Glean is disabled and its artifacts are removed
  hosts: seed:overcloud
  tags:
    - disable-glean
  roles:
    - role: disable-glean
