---
# Generate an environment file for interacting with the public OpenStack APIs
# as the admin user in the admin project.

- name: Ensure a public OpenStack API environment file exists
  hosts: localhost
  tags:
    - public-openrc
  vars:
    public_api_proto: "{% if kolla_enable_tls_external | bool %}https{% else %}http{% endif %}"
    public_api_vip_address: "{{ public_net_name | net_vip_address }}"
    public_api_keystone_port: 5000
  roles:
    - role: public-openrc
      public_openrc_kolla_config_path: "{{ kolla_config_path }}"
      public_openrc_auth_url: "{{ public_api_proto }}://{{ public_api_vip_address }}:{{ public_api_keystone_port }}"
