---
- hosts: controllers
  tags:
    - swift
  roles:
    - role: swift-setup
      swift_image: "kolla/{{ kolla_base_distro }}-{{ kolla_install_type }}-swift-base:{{ kolla_openstack_release }}"
      swift_ring_build_host: "{{ groups['controllers'][0] }}"
      # ID of the region for this Swift service.
      swift_region: 1
      # ID of the zone for this Swift service.
      swift_zone: "{{ groups['controllers'].index(inventory_hostname) % swift_num_zones }}"
      when: kolla_enable_swift | bool
