---
- name: Include OS family-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: installed
  become: True
  with_items: "{{ dev_tools_packages }}"
